version: "3"
services:
  recipes:
    container_name: recipes
    image: recipes:latest
    build:
      context: ./Source
      dockerfile: ../Dockerfile
    environment:
      - RECIPES_DB_USER=${RECIPES_DB_USER}
      - RECIPES_DB_HOST=${RECIPES_DB_HOST}
      - RECIPES_DB_PASSWORD=${RECIPES_DB_PASSWORD}
      - VIRTUAL_HOST=${RECIPES_VIRTUAL_HOST}
    expose:
      - 80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "unless-stopped"
    tty: true
